hugoblox:
  schema: "2.0"
  identity:
    name: Cheuk Hei Matthew Tam
    type: person
    tagline: "Unmanned Aerial Vehicle Enthusiast | Cranfield Manchester "
    description: I am currently a Master of Science student in Cranfield University, United Kingdom. I recieved my Bachelor of Aerospace Engineering in Manchester in 2025.
    organization: Cranfield University
  theme:
    mode: system
    pack: default
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: serif
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
